<div class="sidebar-block sidebar-suggestion">
  <div class="sidebar-title">
    suggestion box
  </div>
  <div class="sidebar-content">
    <form>
      <div class="form-item">
        <textarea cols="30" rows="10" class="form-textarea"></textarea>
      </div>
      <div class="button-submit">
        <div class="form-item">
          <input class="form-submit" type="submit" value="Send">
        </div>
      </div>
    </form>
  </div>
</div>