<?php

define("OCT_LINE_ITEM_KEY_NAME", "oct_discounts");
define("OCT_LINE_ITEM_FREE_MANUAL_KEY_NAME", "oct_free_discounts");
define("OCT_LINE_ITEM_FEE_KEY_NAME", "fee");

define("OCT_LINE_ITEM_WEIGHT", 1);
define("OCT_CALCULATE_DISCOUNT_RESPONSE_LINE_ITEMS_KEY", "line_items");
define("OCT_CALCULATE_DISCOUNT_RESPONSE_ERRORS_KEY", "errors");
define("OCT_CALCULATE_DISCOUNT_RESPONSE_MESSAGES_KEY", "messages");
define("OCT_CALCULATE_DISCOUNT_RESPONSE_SUBTOTAL", 'table_subtotal');

/**
 * @file
 * Site-related functionnality
 *
 * @author
 * Sergey Grigorenko
 * @package OCT
 */

/**
 * Implements hook_theme().
 */
function oct_discounts_theme() {
    return array(
        'oct_discounts_cart_checkout_table' => array(
            'arguments' => array('form' => NULL),
        ),
    );
}

/**
 * implementation of hook_menu_aletr()
 */
function oct_discounts_menu_alter(&$menu){

  //set own count fee;
  //$menu['cart/checkout/line_items']['page callback'] = 'oct_custom_payment_get_totals';
  
}

/**
 * Implementation of hook_init
 */
function oct_discounts_init(){
  module_load_include('inc', 'oct_discounts', 'uc_panes');
  drupal_add_css(drupal_get_path('module','oct_discounts')."/templates/css/oct_discounts.css");
  drupal_add_css(drupal_get_path('module','oct_discounts')."/templates/css/uc_discounts.css");
  drupal_add_js(array(
                  'oct_discounts' => array(
                        'line_item_key_name' => OCT_LINE_ITEM_KEY_NAME,
                        'line_item_weight' => OCT_LINE_ITEM_WEIGHT,
                        'total_discount_text' => t('Total discount'),
                        'calculate_discount_response_line_items_key' => OCT_CALCULATE_DISCOUNT_RESPONSE_LINE_ITEMS_KEY,
                        'calculate_discount_response_errors_key' => OCT_CALCULATE_DISCOUNT_RESPONSE_ERRORS_KEY,
                        'calculate_discount_response_messages_key' => OCT_CALCULATE_DISCOUNT_RESPONSE_MESSAGES_KEY,
                        'calculate_discount_response_subtotal' => OCT_CALCULATE_DISCOUNT_RESPONSE_SUBTOTAL,
                        'progress_msg' => t('Calculating discounts...'),
                        'no_codes_entered' => t('Please enter at least one code'),
                        'no_applicable_discounts' => t('No applicable discounts'),
                        'err_msg' => t('There were problems determining if any discounts apply.  Please try again shortly.\nIf this does not resolve the issue, please call @phone to complete your order.', array('@phone' => variable_get('uc_store_phone', NULL))),
                        'response_parse_err_msg' => t('Unable to parse response text: '),
                    ),
                ), 'setting');
  drupal_add_js(drupal_get_path('module','oct_discounts')."/templates/js/oct_discounts.js");
}

/**
 * Implementation of hook_menu().
 */
function oct_discounts_menu() {
    
  $items['cart/checkout/oct_discounts/calculate'] = array(
        'page callback'     => 'get_oct_custom_discounts',
        'access arguments'  => array('access content'),
        'file'              => 'uc_panes.inc',
        'type'              => MENU_CALLBACK
  );

  return $items;
}

/**
 *  Implementation of hook_form_alter
 */
function oct_discounts_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    switch($form_id){
      case 'discounts_node_form': // DISCOUNT ADMIN FORM
          drupal_add_js('Drupal.behaviors.editDiscountNode = function(context){ editDiscount();}', 'inline');
          if (in_array('manager', $user->roles)) {
              $form['field_discount_weight']['#access'] = false;
          }
          break;
      case 'uc_cart_checkout_form':
          $form['#submit'][] = 'resave_order_after_checkout_submit';
          drupal_add_js('Drupal.behaviors.editDiscountNode = function(context){ octDiscountCount();}', 'inline');
          break;
    }
}

/**
 * hook_uc_cart_alter
 * @param type $items 
 */
function oct_discounts_uc_cart_alter(&$items){
    // sort items in cart
    usort($items, 'oct_discounts_uc_cart_sort_function');
}


/**
 * Sort function for usort();
 * @param stdClass $a
 * @param stdClass $b
 * @return boolean 
 */
function oct_discounts_uc_cart_sort_function($a, $b){
    return ($a->cart_item_id < $b->cart_item_id) ? -1 : 1;
}


/**
 * hook_uc_checkout_complete
 * @param stdClass $order
 * @param stdClass $account 
 */
function oct_discounts_uc_checkout_complete($order, $account){

/*
    if(!empty($_SESSION['uc_discounts_codes'])){
        $code = $_SESSION['uc_discounts_codes'];
    }

    $errors = array();
    $warnings = array();
    $messages = array();

    $discount_items = get_all_discount($order, $errors, $warnings, $messages, $code);
    //count total pay 
    $total_pay_amount = 0;
    if(!empty ($order->line_items) && is_array($order->line_items)){
        foreach($order->line_items as $items){
             $total_pay_amount += $items['amount'];
        }
    }
    if(!empty ($discount_items) && is_array($discount_items)){
        foreach($discount_items as $discount){
             $total_pay_amount += $discount['amount'];
        }
    }
    $order->order_total = $total_pay_amount;
 */
}
